name: Despliegue Automático

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y publicar imagen
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/mi-app:latest .
          docker push ${{ secrets.DOCKER_USER }}/mi-app:latest

      - name: Desplegar en AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USER }}/mi-app:latest
            sudo docker stop mi-app || true
            sudo docker rm mi-app || true
            sudo docker run -d -p 80:80 --name mi-app ${{ secrets.DOCKER_USER }}/mi-app:latest